services:
 
  db:
    image: postgres
    restart: always
    environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 7287
          POSTGRES_DB: nest
    ports:
      - 5434:5432
